version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:10000

  server:
    build: ./server
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:3000
